serverHTTP:
  writeTimeout: 60s
database:
  url: postgres://DB_USER:DB_PASSWORD@DB_HOST:DB_PORT/DB_NAME?sslmode=disable
  migrations:
    apply: true
    version: 6
cloudStorage:
  enabled: true
  bucketMultimedia: multimedia_bucket
smtp:
  enabled: true
  host: SMTP_HOST
  port: SMTP_PORT
  username: SMTP_USERNAME
  password: SMTP_PASSWORD
  from: SMTP_FROM
