openapi: "3.0.0"
info:
  version: 1.0.0
  title: GOOFR Store REST API
tags:
  - name: User
    description: User operations
servers:
  - url: https://TODO/api
    description: Production server.
  - url: http://localhost:8080/api
    description: Local server.

paths:
  /users:
    post:
      summary: Create a user.
      operationId: createUser
      description: Creates a new user with the specified data.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPost"
      responses:
        201:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid request body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        409:
          description: Username, email or vatin already exists. Or multimedia does not exist.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      required:
        - code
      properties:
        code:
          type: string
        message:
          type: string
    UUID:
      type: string
      format: uuid
      example: "9e3a65b0-0579-4203-8112-d09ab3c6b1ff"
    Date:
      type: string
      format: date
      example: "2017-07-21"
    DateTime:
      type: string
      format: date-time
      example: "2017-07-21T17:32:28Z"
    Username:
      type: string
      minLength: 1
      maxLength: 50
      example: john-doe
    Email:
      type: string
      maxLength: 320
      example: john-doe@email.com
    Password:
      type: string
      format: password
      description: In addition to the length restrictions, the password must contain at least one regular character, one special character, and one number.
      minLength: 14
      maxLength: 72
      example: ReallySecurePassword$123
    Name:
      type: string
      minLength: 1
      maxLength: 100
      example: John Doe
    Address:
      type: string
      minLength: 1
      maxLength: 100
    Country:
      type: string
      description: BCP 47 language tag.
      minLength: 1
      maxLength: 20
    Vatin:
      type: string
      minLength: 1
      maxLength: 20

    UserBalance:
      type: number
      format: double

    UserPost:
      type: object
      required:
        - username
        - email
        - password
        - displayName
        - dateOfBirth
        - address
        - country
        - vatin
      properties:
        username:
          $ref: "#/components/schemas/Username"
        email:
          $ref: "#/components/schemas/Email"
        password:
          $ref: "#/components/schemas/Password"
        displayName:
          $ref: "#/components/schemas/Name"
        dateOfBirth:
          $ref: "#/components/schemas/Date"
        address:
          $ref: "#/components/schemas/Address"
        country:
          $ref: "#/components/schemas/Country"
        vatin:
          $ref: "#/components/schemas/Vatin"
        pictureMultimediaId:
          $ref: "#/components/schemas/UUID"
    User:
      type: object
      required:
        - id
        - username
        - email
        - displayName
        - dateOfBirth
        - address
        - country
        - vatin
        - balance
        - createdAt
        - modifiedAt
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        username:
          $ref: "#/components/schemas/Username"
        email:
          $ref: "#/components/schemas/Email"
        displayName:
          $ref: "#/components/schemas/Name"
        dateOfBirth:
          $ref: "#/components/schemas/Date"
        address:
          $ref: "#/components/schemas/Address"
        country:
          $ref: "#/components/schemas/Country"
        vatin:
          $ref: "#/components/schemas/Vatin"
        balance:
          $ref: "#/components/schemas/UserBalance"
        pictureMultimediaId:
          $ref: "#/components/schemas/UUID"
        createdAt:
          $ref: "#/components/schemas/DateTime"
        modifiedAt:
          $ref: "#/components/schemas/DateTime"

  responses:
    Unauthorized:
      description: Access token is missing or invalid.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Forbidden:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
